name: Build and deploy to GH Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build static page
        run: npm run build
      - name: Create static page artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        id: deployment
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
